### ISSUE TITLE
Could'nt find symbol ltspice

### ISSUE THREAD

**Issue by Alan9890** [PolyCortex/AcquisitionEEG#1]
To do the design simulation some components symbols are required , where you can get them?
Or if you could provide them in the repository to add in LTSpice. 
The Ltspice message for :
Could'nt find symbol ltspice
res
UniversalOpamp2
cap
voltage
signal
AD8429

**Comment by conorato** [comment]
Hi! The installation of LTSpice should also come with these symbols, that are defined in the /lib folder in the LTSpace application folder. On Mac, per example, you have to right click on the application, click on `show package content`, go to `Contents/Resources/lib`.

The problem may be when you select the top directory where LTSpice looks for the symbols (as you can see below).

<img width="454" alt="image" src="https://user-images.githubusercontent.com/17006104/81433736-103cc880-9133-11ea-87a1-8ed6b267767c.png">

**Comment by Alan9890** [comment]
Hello
To solve this issue I just had to change the name of the component cause your design has different name (Opamp -> UniversalOpamp2), but I've not found the right  AD8429 component in library directory.
